const html = `<style>
a.cky-banner-element {
  padding: 8px 30px;
  background: #FBEB00;
  color: #27272A;
  border: 1px solid #FBEB00;
  box-sizing: border-box;
  border-radius: 6px;
  cursor: pointer;
}
  a.cky-banner-element:hover {
    background: #eab308;
    border: 1px solid #eab308;
  }
</style>
<p>
    Effective Date: 10-Nov-2024 <br>
    Last Updated: 10-Nov-2024
</p>
<h3>What are cookies?</h3>
<div class="cookie-policy-p"><p>This Cookie Policy explains what cookies are and how we use them, the types of cookies we use i.e, the information we collect using cookies and how that information is used, and how to manage the cookie settings.</p> <p>Cookies are small text files that are used to store small pieces of information. They are stored on your device when the website is loaded on your browser. These cookies help us make the website function properly, make it more secure, provide better user experience, and understand how the website performs and to analyze what works and where it needs improvement.</p></div>

<h3>How do we use cookies?</h3>
<div class="cookie-policy-p"><p>As most of the online services, our website uses first-party and third-party cookies for several purposes. First-party cookies are mostly necessary for the website to function the right way, and they do not collect any of your personally identifiable data.</p> <p>The third-party cookies used on our website are mainly for understanding how the website performs, how you interact with our website, keeping our services secure, providing advertisements that are relevant to you, and all in all providing you with a better and improved user experience and help speed up your future interactions with our website.</p></div>

    <h3>Cookie Policy</h3>

    <div class="cky-audit-table-element"></div>

    <h3 style="margin-bottom:20px;">Manage cookie preferences</h3>

    <a class="cky-banner-element">Cookie Settings</a> <br/>

    <div><p>You can change your cookie preferences any time by clicking the above button. This will let you revisit the cookie consent banner and change your preferences or withdraw your consent right away. </p> <p>In addition to this, different browsers provide different methods to block and delete cookies used by websites. You can change the settings of your browser to block/delete the cookies. Listed below are the links to the support documents on how to manage and delete cookies from the major web browsers.</p> <p>Chrome: <a target="_blank" href="https://support.google.com/accounts/answer/32050">https://support.google.com/accounts/answer/32050</a></p><p>Safari: <a target="_blank" href="https://support.apple.com/en-in/guide/safari/sfri11471/mac">https://support.apple.com/en-in/guide/safari/sfri11471/mac</a></p><p>Firefox: <a target="_blank" href="https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox?redirectslug=delete-cookies-remove-info-websites-stored&amp;redirectlocale=en-US">https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox?redirectslug=delete-cookies-remove-info-websites-stored&amp;redirectlocale=en-US</a></p><p>Internet Explorer: <a target="_blank" href="https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc">https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc</a></p><p>If you are using any other web browser, please visit your browser’s official support documents.</p></div>

<p class="cookie-policy-p">
    Cookie Policy Generated By  <a target="_blank" href="https://www.cookieyes.com/?utm_source=CP&utm_medium=footer&utm_campaign=UW">CookieYes - Cookie Policy Generator</a>.
</p>`
export default function CookiePage() {
  return (
    <main className='lg:mt-12 max-w-7xl mx-6 md:mx-12 lg:mx-auto overflow-x-hidden'>
      <div className='flex flex-col gap-y-16'>
        <div className='max-w-4xl justify-start'>
          <h1 className='text-4xl lg:text-8xl font-black text-left'>
            <span className='text-transparent bg-clip-text bg-gradient-to-r from-primary to-yellow-600'>Big</span> Cookie Policy
          </h1>
        </div>
        <div className='mx-auto max-w-4xl prose prose-pixel'>
          <div dangerouslySetInnerHTML={{ __html: html }} />
        </div>
      </div>
    </main>
  )
}